Feat/model/user
Recursion-Group-K/sketch pull request #13
Opened 2022-01-13 10:01 UTC by tkwonn

#12 

エラー解消次第、api/userWrapper.jsおよびtest/userWrapperTest.jsはfeat/mock/Userブランチに移してこのブランチからは消します。

2022-01-13 10:18 UTC, mcnLeandro reviewed
自分もなぜかは説明できないですが、自分の環境では
babael.config.js => babel.config.cjs
package.jsonを以下のように変更すると動きました！

2022-01-13 10:18 UTC, mcnLeandro commented on package.json
> +  "type": "module",
```suggestion
  "type": "commonjs",
```

2022-01-13 10:31 UTC, mcnLeandro commented
https://babeljs.io/docs/en/config-files#supported-file-extensions

> babel.config.cjs and .babelrc.cjs allow you to define your configuration as CommonJS, using module.exports. They have been supported since v7.7.0.

https://qiita.com/riversun/items/6c30a0d0897194677a37

まだよくわからないです笑

2022-01-13 10:48 UTC, tkwonn commented
すごいです。。
では、エラーを解消して、各処理ごとに該当するブランチに記入し直してプルリクエストを送りなおしますね！

2022-01-13 13:45 UTC, mcnLeandro commented
jest使うかもです。

2022-01-13 14:05 UTC, mcnLeandro commented
2a898de70e6818a7b4f9936857f9cbbc77a91125

こちらのコミットで成功しました！
nodeでのjavascriptのテストはファイルを実行しているだけで、サーバーを立てないので、ファイル同士でCORSエラーが起きているとのことだったので、サーバーを立てたテストをする => jest使おうと言う流れになりました！
自分もjestは初めてなのでいい経験ですね。

せっかくなので、kwonさんも自分でやってみるといいです！
https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-unit-jest

```
vue add unit-jest
```
babel.config.js => babel.cjs

package.json ... type: commonjs

あとは、testsフォルダを真似してみてください！

commit 2a898de70e6818a7b4f9936857f9cbbc77a91125

あと、testsフォルダの階層が変わっているので注意してください。[こちら](https://github.com/Recursion-Group-K/memo/blob/main/FileTree.md)も書き換えておきます。

ファイル構成の仕様が度々変わっちゃってすみません😅
こんな感じで、またあるかもなのでよろしくお願いします！

2022-01-13 23:44 UTC, tkwonn commented
@mcnLeandro さん、ありがとうございます！自分でもやってみますね。でき次第、こちらのブランチではmodels/user.jsのみを加えて、mock/Userブランチに変更を加えたtest/unit, api/userWrapperTest.js, babel, package.jsonを追加してプルリクエストを送るという認識でよろしいでしょうか？

2022-01-14 04:39 UTC, mcnLeandro commented
@tkwonn 
そうです！
それでお願いします！

2022-01-15 00:30 UTC, tkwonn commented
Revertを行い、Userモデルだけを追加したものをこのブランチに追加しました！
確認お願いします！

2022-01-15 02:21 UTC, mcnLeandro requested changes
細かいですが、

a140c00
こちらのコミットをrevertしてlintし直すか

.eslintrc.jsを #15 で言及してる書き方に変更していただけたら嬉しいです！

2022-01-15 04:35 UTC, tkwonn commented
了解です！！

2022-01-15 16:35 UTC, mcnLeandro approved these changes
ありがとうございます！
これで一旦OKです！

レビューが遅れちゃったので、このままでOKですが、書き方にアドバイスがあるので、シェアしておきますね！

2022-01-15 16:35 UTC, mcnLeandro commented on src/models/user.js
> +    }
ここはこう言う書き方もあります！

```js
 constructor({id, name, email, password}) {
        this.id = params.id;
        this.name = params.name;
        this.email = params.email;
        this.password = params.password;
    }
```

2022-01-15 16:39 UTC, merged