feat/mock/User
Recursion-Group-K/sketch pull request #14
Opened 2022-01-15 01:30 UTC by tkwonn

行った事：

src/api/userWrapper.js
vue add unit-jestでtests/unit/userWrapperTest.spec.js
の２つを新たに作成
（Userモデルがないためimport文はコメントアウト）

テスト結果：
![Screen Shot 2022-01-14 at 17 29 39](https://user-images.githubusercontent.com/66197642/149603737-0e71fe0a-8f92-4929-99f0-de1ba1d196fc.png)

2022-01-15 16:43 UTC, mcnLeandro requested changes
レビュー遅れてすみません！

#13 userモデルのプルリクをマージしたので、一旦developをpullして、コンフリクト解消（あれば）してから、new Userのコメントアウトを外してください！🙏

2022-01-15 20:48 UTC, tkwonn commented
了解です！

2022-01-16 02:00 UTC, tkwonn commented
package-lock.jsonのコンフリクトに関してですが、以下のサイトを参考に解消しようと試みましたが、package-lock.json内のコンフリクトは解消されていないようです。

https://flutterq.com/deleting-package-lock-json-to-resolve-conflicts-quickly/

npm run test:unit, npm run serve, npm run lintは正常に動きます。

2022-01-16 04:25 UTC, mcnLeandro commented
いい方法ではないかもですが、npm install を行うといいですよ！

2022-01-16 06:02 UTC, tkwonn commented
ありがとうございます！できました！ここで変更を加えてよかったのかわかりませんが、LoginページからSignInページへのリンク、SignInページからLoginページへ移るページもページ同士がマージされていたので該当するリンクに修正しておきました！

ご確認お願いします！

2022-01-16 06:58 UTC, mcnLeandro requested changes
レビューしました！

2022-01-16 06:58 UTC, mcnLeandro commented on src/api/userWrapper.js
> +}
こちら、コンフリクトの際に出てくる
<<<みたいなのが残ってしまってますね笑笑

- こちら修正していただいて、
- `reutrn new User(params)` の部分のコメントアウトを外して
- テストをしてログが確認できるか確認

お願いします！

2022-01-16 06:58 UTC, mcnLeandro commented on src/api/userWrapper.js
> +            };
```suggestion
            const { id, name, email, username } = responce.data
            const params = {
                id: id,
                name: name,
                email: email,
                password: username,
            };
```

分割代入を使ってみるとちょっとDRYを意識できます！

2022-01-16 07:17 UTC, tkwonn commented on src/api/userWrapper.js
> +}
すみません！確認不足でした！

2022-01-16 07:22 UTC, tkwonn commented on src/api/userWrapper.js
> +            };
承知いたしました！

2022-01-16 07:24 UTC, tkwonn commented on src/api/userWrapper.js
> +    async getById(userId) {
こちらの引数は分割代入を使用する際にidという変数を使い、被ってしまうので id -> userId へ変更しました！

2022-01-16 07:27 UTC, tkwonn commented on src/api/userWrapper.js
> +}
const paramsの複数形にしたほうがいい所をparamと単数形にしてしまったのですが、こちら修正したほうがよろしいですかね？

2022-01-16 07:28 UTC, tkwonn commented on src/api/userWrapper.js
> +            const param = {
const paramsの複数形にすべき所を単数形のparamと書いてしまった事にいま気づいたのですが、こちら修正したほうがいいですかね？

2022-01-16 07:43 UTC, mcnLeandro commented on src/api/userWrapper.js
> +    async getById(userId) {
ごめんなさいそこまで頭が回ってなかったです！

分割代入で違う変数名をつけることができるみたいなのでそっちの方がいいかも。。と思ったり、
どう思いますか？

https://qiita.com/mqtsuo02/items/fd18ceab4fd363b84634

2022-01-16 07:43 UTC, mcnLeandro commented on src/api/userWrapper.js
> +            const param = {
そうですね！
変えておいていただけると！

2022-01-16 08:41 UTC, tkwonn commented on src/api/userWrapper.js
> +    async getById(userId) {
いえいえ！　このような感じで大丈夫ですかね？
```
async getById(id) {
        try {
            const response = await axios.get(`https://jsonplaceholder.typicode.com/users/${id}`);
            const { id: userId, name, email, username: password } = response.data;
            const params = {
                id: userId,
                name: name,
                email: email,
                password: password,
            };
            return new User(params);
        } catch (error) {
            console.log(error);
        }
    }
```

2022-01-16 08:54 UTC, mcnLeandro commented on src/api/userWrapper.js
> +    async getById(userId) {
ありがとうございます！そうですね！これでOKです！
助かります！

2022-01-16 11:04 UTC, tkwonn commented
これで大丈夫かと思います！
みなさん、レビューお願いします！

2022-01-16 12:15 UTC, mcnLeandro approved these changes
OKです！

2022-01-17 01:15 UTC, merged